on: pull_request
name: pr. Remove label dismissed pull requests
jobs:
  removeLabelWhenDismissed:
    name: Remove label dismissed pull requests
    runs-on: ubuntu-latest
    steps:
    - name: Remove label dismissed pull requests
      run: |
        URI="https://api.github.com"
        API_HEADER="Accept: application/vnd.github.v3+json"
        AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
        number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        base=$(jq --raw-output .pull_request.base.ref "$GITHUB_EVENT_PATH")
        echo $number
        echo $base
        if [[ "$base" == "master" ]]; then
          curl -sSL \
                -H "${AUTH_HEADER}" \
                -H "${API_HEADER}" \
                -X DELETE \
                "${URI}/repos/${GITHUB_REPOSITORY}/issues/${number}/labels/${REMOVE_LABEL}"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REMOVE_LABEL: "approved"
