on: push
name: Remove label dismissed pull requests
jobs:
  removeLabelWhenDismissed:
    name: Remove label dismissed pull requests
    runs-on: ubuntu-latest
    steps:
    - name: Remove label dismissed pull requests
      uses: fan-y-sasaki/label-when-approved-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REMOVE_LABEL: "approved"
