on: push
name: Remove label dismissed pull requests
jobs:
  removeLabelWhenDismissed:
    name: Remove label dismissed pull requests
    runs-on: ubuntu-latest
    steps:
    - name: Remove label dismissed pull requests
      run: |
        echo "This is test log"
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
        REMOVE_LABEL: "approved"
