name: Label when approved or remove label when dismissed

on: pull_request_review
jobs:
  prLabeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Labeling
      uses: yotasasaki/test/.github/actions/pr-labeler@master
      env:
        APPROVALS: "2"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "releasable"
